services:
  receiver:
    build: ./receiver
    container_name: kubepulse-receiver
    env_file: .env
    ports:
      - "8088:8080"
    restart: unless-stopped

  bot:
    build: ./bot
    container_name: kubepulse-telegram-bot
    env_file: .env
    depends_on:
      - receiver
    restart: unless-stopped